# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 15:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wotlogin', '0002_dic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petname', models.CharField(max_length=100)),
                ('pettype', models.CharField(max_length=100)),
                ('petbreed', models.CharField(max_length=100)),
                ('petbirthday', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PetDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userkeyword', models.CharField(max_length=10000)),
                ('addedkeyword', models.CharField(max_length=10000)),
                ('potentialkeyword', models.CharField(max_length=10000)),
                ('date', models.DateTimeField()),
                ('disease', models.CharField(max_length=10000)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wotlogin.Pet')),
            ],
        ),
    ]
