# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wotlogin', '0003_pet_petdisease'),
    ]

    operations = [
        migrations.AddField(
            model_name='petdisease',
            name='discription',
            field=models.CharField(default=' ', max_length=10000),
            preserve_default=False,
        ),
    ]
